//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SystemModels {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("MsgPack.Serialization.CodeDomSerializers.CodeDomSerializerBuilder", "1.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public class SystemModels_DataTypeFileSerializer : MsgPack.Serialization.MessagePackSerializer<SystemModels.DataTypeFile> {
        
        private System.Reflection.FieldInfo _fieldBaseClass__msgPackDummyField0;
        
        private MsgPack.Serialization.MessagePackSerializer<byte> _serializer0;
        
        private System.Reflection.FieldInfo _fieldDataTypeFile___core_Поле11;
        
        private MsgPack.Serialization.MessagePackSerializer<string> _serializer1;
        
        private System.Collections.Generic.IList<System.Action<MsgPack.Packer, SystemModels.DataTypeFile>> _packOperationList;
        
        private System.Collections.Generic.IDictionary<string, System.Action<MsgPack.Packer, SystemModels.DataTypeFile>> _packOperationTable;
        
        private System.Collections.Generic.IDictionary<string, System.Func<SystemModels.DataTypeFile, bool>> _nullCheckersTable;
        
        private System.Action<SystemModels.DataTypeFile, byte> this_SetUnpackedValueOf_msgPackDummyFieldDelegate;
        
        private System.Func<MsgPack.Unpacker, System.Type, string, byte> MsgPack_Serialization_UnpackHelpers_UnpackByteValueDelegate;
        
        private System.Action<SystemModels.DataTypeFile, string> this_SetUnpackedValueOf__core_Поле1Delegate;
        
        private System.Func<MsgPack.Unpacker, System.Type, string, string> MsgPack_Serialization_UnpackHelpers_UnpackStringValueDelegate;
        
        private System.Collections.Generic.IList<string> _memberNames;
        
        private System.Collections.Generic.IList<System.Action<MsgPack.Unpacker, SystemModels.DataTypeFile, int, int>> _unpackOperationList;
        
        private System.Collections.Generic.IDictionary<string, System.Action<MsgPack.Unpacker, SystemModels.DataTypeFile, int, int>> _unpackOperationTable;
        
        public SystemModels_DataTypeFileSerializer(MsgPack.Serialization.SerializationContext context) : 
                base(context, (MsgPack.Serialization.SerializerCapabilities.PackTo | MsgPack.Serialization.SerializerCapabilities.UnpackFrom)) {
            MsgPack.Serialization.PolymorphismSchema schema0 = default(MsgPack.Serialization.PolymorphismSchema);
            schema0 = null;
            this._serializer0 = context.GetSerializer<byte>(schema0);
            MsgPack.Serialization.PolymorphismSchema schema1 = default(MsgPack.Serialization.PolymorphismSchema);
            schema1 = null;
            this._serializer1 = context.GetSerializer<string>(schema1);
            this._fieldBaseClass__msgPackDummyField0 = MsgPack.Serialization.ReflectionHelpers.GetField(typeof(SystemModels.BaseClass), "_msgPackDummyField");
            this._fieldDataTypeFile___core_Поле11 = MsgPack.Serialization.ReflectionHelpers.GetField(typeof(SystemModels.DataTypeFile), "__core_Поле1");
            System.Action<MsgPack.Packer, SystemModels.DataTypeFile>[] packOperationList = default(System.Action<MsgPack.Packer, SystemModels.DataTypeFile>[]);
            packOperationList = new System.Action<MsgPack.Packer, SystemModels.DataTypeFile>[2];
            packOperationList[0] = new System.Action<MsgPack.Packer, SystemModels.DataTypeFile>(this.PackValueOf_msgPackDummyField);
            packOperationList[1] = new System.Action<MsgPack.Packer, SystemModels.DataTypeFile>(this.PackValueOf__core_Поле1);
            this._packOperationList = packOperationList;
            System.Collections.Generic.Dictionary<string, System.Action<MsgPack.Packer, SystemModels.DataTypeFile>> packOperationTable = default(System.Collections.Generic.Dictionary<string, System.Action<MsgPack.Packer, SystemModels.DataTypeFile>>);
            packOperationTable = new System.Collections.Generic.Dictionary<string, System.Action<MsgPack.Packer, SystemModels.DataTypeFile>>(2);
            packOperationTable["_msgPackDummyField"] = new System.Action<MsgPack.Packer, SystemModels.DataTypeFile>(this.PackValueOf_msgPackDummyField);
            packOperationTable["__core_Поле1"] = new System.Action<MsgPack.Packer, SystemModels.DataTypeFile>(this.PackValueOf__core_Поле1);
            this._packOperationTable = packOperationTable;
            System.Collections.Generic.Dictionary<string, System.Func<SystemModels.DataTypeFile, bool>> nullCheckerTable = default(System.Collections.Generic.Dictionary<string, System.Func<SystemModels.DataTypeFile, bool>>);
            nullCheckerTable = new System.Collections.Generic.Dictionary<string, System.Func<SystemModels.DataTypeFile, bool>>(1);
            nullCheckerTable["__core_Поле1"] = new System.Func<SystemModels.DataTypeFile, bool>(this.Is__core_Поле1Null);
            this._nullCheckersTable = nullCheckerTable;
            System.Action<MsgPack.Unpacker, SystemModels.DataTypeFile, int, int>[] unpackOperationList = default(System.Action<MsgPack.Unpacker, SystemModels.DataTypeFile, int, int>[]);
            unpackOperationList = new System.Action<MsgPack.Unpacker, SystemModels.DataTypeFile, int, int>[2];
            unpackOperationList[0] = new System.Action<MsgPack.Unpacker, SystemModels.DataTypeFile, int, int>(this.UnpackValueOf_msgPackDummyField);
            unpackOperationList[1] = new System.Action<MsgPack.Unpacker, SystemModels.DataTypeFile, int, int>(this.UnpackValueOf__core_Поле1);
            this._unpackOperationList = unpackOperationList;
            System.Collections.Generic.Dictionary<string, System.Action<MsgPack.Unpacker, SystemModels.DataTypeFile, int, int>> unpackOperationTable = default(System.Collections.Generic.Dictionary<string, System.Action<MsgPack.Unpacker, SystemModels.DataTypeFile, int, int>>);
            unpackOperationTable = new System.Collections.Generic.Dictionary<string, System.Action<MsgPack.Unpacker, SystemModels.DataTypeFile, int, int>>(2);
            unpackOperationTable["_msgPackDummyField"] = new System.Action<MsgPack.Unpacker, SystemModels.DataTypeFile, int, int>(this.UnpackValueOf_msgPackDummyField);
            unpackOperationTable["__core_Поле1"] = new System.Action<MsgPack.Unpacker, SystemModels.DataTypeFile, int, int>(this.UnpackValueOf__core_Поле1);
            this._unpackOperationTable = unpackOperationTable;
            this._memberNames = new string[] {
                    "_msgPackDummyField",
                    "__core_Поле1"};
            this.this_SetUnpackedValueOf_msgPackDummyFieldDelegate = new System.Action<SystemModels.DataTypeFile, byte>(this.SetUnpackedValueOf_msgPackDummyField);
            this.MsgPack_Serialization_UnpackHelpers_UnpackByteValueDelegate = new System.Func<MsgPack.Unpacker, System.Type, string, byte>(MsgPack.Serialization.UnpackHelpers.UnpackByteValue);
            this.this_SetUnpackedValueOf__core_Поле1Delegate = new System.Action<SystemModels.DataTypeFile, string>(this.SetUnpackedValueOf__core_Поле1);
            this.MsgPack_Serialization_UnpackHelpers_UnpackStringValueDelegate = new System.Func<MsgPack.Unpacker, System.Type, string, string>(MsgPack.Serialization.UnpackHelpers.UnpackStringValue);
        }
        
        private void PackValueOf_msgPackDummyField(MsgPack.Packer packer, SystemModels.DataTypeFile objectTree) {
            this._serializer0.PackTo(packer, ((byte)(this._fieldBaseClass__msgPackDummyField0.GetValue(objectTree))));
        }
        
        private void PackValueOf__core_Поле1(MsgPack.Packer packer, SystemModels.DataTypeFile objectTree) {
            this._serializer1.PackTo(packer, ((string)(this._fieldDataTypeFile___core_Поле11.GetValue(objectTree))));
        }
        
        private bool Is__core_Поле1Null(SystemModels.DataTypeFile objectTree) {
            return (((string)(this._fieldDataTypeFile___core_Поле11.GetValue(objectTree))) == null);
        }
        
        protected override void PackToCore(MsgPack.Packer packer, SystemModels.DataTypeFile objectTree) {
            MsgPack.Serialization.PackToArrayParameters<SystemModels.DataTypeFile> packHelperParameters = default(MsgPack.Serialization.PackToArrayParameters<SystemModels.DataTypeFile>);
            packHelperParameters.Packer = packer;
            packHelperParameters.Target = objectTree;
            packHelperParameters.Operations = this._packOperationList;
            MsgPack.Serialization.PackToMapParameters<SystemModels.DataTypeFile> packHelperParameters0 = default(MsgPack.Serialization.PackToMapParameters<SystemModels.DataTypeFile>);
            packHelperParameters0.Packer = packer;
            packHelperParameters0.Target = objectTree;
            packHelperParameters0.Operations = this._packOperationTable;
            packHelperParameters0.SerializationContext = this.OwnerContext;
            packHelperParameters0.NullCheckers = this._nullCheckersTable;
            if ((this.OwnerContext.SerializationMethod == MsgPack.Serialization.SerializationMethod.Array)) {
                MsgPack.Serialization.PackHelpers.PackToArray(ref packHelperParameters);
            }
            else {
                MsgPack.Serialization.PackHelpers.PackToMap(ref packHelperParameters0);
            }
        }
        
        private void SetUnpackedValueOf_msgPackDummyField(SystemModels.DataTypeFile unpackingContext, byte unpackedValue) {
            this._fieldBaseClass__msgPackDummyField0.SetValue(unpackingContext, ((object)(unpackedValue)));
        }
        
        private void UnpackValueOf_msgPackDummyField(MsgPack.Unpacker unpacker, SystemModels.DataTypeFile unpackingContext, int indexOfItem, int itemsCount) {
            MsgPack.Serialization.UnpackValueTypeValueParameters<SystemModels.DataTypeFile, byte> unpackHelperParameters = default(MsgPack.Serialization.UnpackValueTypeValueParameters<SystemModels.DataTypeFile, byte>);
            unpackHelperParameters.Unpacker = unpacker;
            unpackHelperParameters.UnpackingContext = unpackingContext;
            unpackHelperParameters.Serializer = this._serializer0;
            unpackHelperParameters.ItemsCount = itemsCount;
            unpackHelperParameters.Unpacked = indexOfItem;
            unpackHelperParameters.TargetObjectType = typeof(byte);
            unpackHelperParameters.MemberName = "_msgPackDummyField";
            unpackHelperParameters.DirectRead = this.MsgPack_Serialization_UnpackHelpers_UnpackByteValueDelegate;
            unpackHelperParameters.Setter = this.this_SetUnpackedValueOf_msgPackDummyFieldDelegate;
            MsgPack.Serialization.UnpackHelpers.UnpackValueTypeValue(ref unpackHelperParameters);
        }
        
        private void SetUnpackedValueOf__core_Поле1(SystemModels.DataTypeFile unpackingContext, string unpackedValue) {
            this._fieldDataTypeFile___core_Поле11.SetValue(unpackingContext, unpackedValue);
        }
        
        private void UnpackValueOf__core_Поле1(MsgPack.Unpacker unpacker, SystemModels.DataTypeFile unpackingContext, int indexOfItem, int itemsCount) {
            MsgPack.Serialization.UnpackReferenceTypeValueParameters<SystemModels.DataTypeFile, string> unpackHelperParameters0 = default(MsgPack.Serialization.UnpackReferenceTypeValueParameters<SystemModels.DataTypeFile, string>);
            unpackHelperParameters0.Unpacker = unpacker;
            unpackHelperParameters0.UnpackingContext = unpackingContext;
            unpackHelperParameters0.Serializer = this._serializer1;
            unpackHelperParameters0.ItemsCount = itemsCount;
            unpackHelperParameters0.Unpacked = indexOfItem;
            unpackHelperParameters0.TargetObjectType = typeof(string);
            unpackHelperParameters0.MemberName = "__core_Поле1";
            unpackHelperParameters0.NilImplication = MsgPack.Serialization.NilImplication.MemberDefault;
            unpackHelperParameters0.DirectRead = this.MsgPack_Serialization_UnpackHelpers_UnpackStringValueDelegate;
            unpackHelperParameters0.Setter = this.this_SetUnpackedValueOf__core_Поле1Delegate;
            MsgPack.Serialization.UnpackHelpers.UnpackReferenceTypeValue(ref unpackHelperParameters0);
        }
        
        protected override SystemModels.DataTypeFile UnpackFromCore(MsgPack.Unpacker unpacker) {
            SystemModels.DataTypeFile result = default(SystemModels.DataTypeFile);
            result = new SystemModels.DataTypeFile();
            if (unpacker.IsArrayHeader) {
                return MsgPack.Serialization.UnpackHelpers.UnpackFromArray(unpacker, result, MsgPack.Serialization.UnpackHelpers.GetIdentity<SystemModels.DataTypeFile>(), this._memberNames, this._unpackOperationList);
            }
            else {
                return MsgPack.Serialization.UnpackHelpers.UnpackFromMap(unpacker, result, MsgPack.Serialization.UnpackHelpers.GetIdentity<SystemModels.DataTypeFile>(), this._unpackOperationTable);
            }
        }
    }
}

