//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SystemModels {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("MsgPack.Serialization.CodeDomSerializers.CodeDomSerializerBuilder", "1.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public class SystemModels_SystemModel_File2FileSerializer : MsgPack.Serialization.MessagePackSerializer<SystemModels.SystemModel.File2File> {
        
        private MsgPack.Serialization.MessagePackSerializer<SystemModels.Message> _serializer0;
        
        private MsgPack.Serialization.MessagePackSerializer<DT.MdmMetadata.CoreEntity.InitialMessageProperty> _serializer1;
        
        private System.Reflection.FieldInfo _fieldFile2File___core_ТипДанныхФайл0;
        
        private MsgPack.Serialization.MessagePackSerializer<SystemModels.ТипДанныхФайл> _serializer2;
        
        private System.Collections.Generic.IList<System.Action<MsgPack.Packer, SystemModels.SystemModel.File2File>> _packOperationList;
        
        private System.Collections.Generic.IDictionary<string, System.Action<MsgPack.Packer, SystemModels.SystemModel.File2File>> _packOperationTable;
        
        private System.Collections.Generic.IDictionary<string, System.Func<SystemModels.SystemModel.File2File, bool>> _nullCheckersTable;
        
        private System.Reflection.MethodBase _methodBaseBaseScope_set_InitMessage0;
        
        private System.Action<SystemModels.SystemModel.File2File, SystemModels.Message> this_SetUnpackedValueOfInitMessageDelegate;
        
        private System.Reflection.MethodBase _methodBaseBaseScope_set_InitData1;
        
        private System.Action<SystemModels.SystemModel.File2File, DT.MdmMetadata.CoreEntity.InitialMessageProperty> this_SetUnpackedValueOfInitDataDelegate;
        
        private System.Action<SystemModels.SystemModel.File2File, SystemModels.ТипДанныхФайл> this_SetUnpackedValueOf__core_ТипДанныхФайлDelegate;
        
        private System.Collections.Generic.IList<string> _memberNames;
        
        private System.Collections.Generic.IList<System.Action<MsgPack.Unpacker, SystemModels.SystemModel.File2File, int, int>> _unpackOperationList;
        
        private System.Collections.Generic.IDictionary<string, System.Action<MsgPack.Unpacker, SystemModels.SystemModel.File2File, int, int>> _unpackOperationTable;
        
        public SystemModels_SystemModel_File2FileSerializer(MsgPack.Serialization.SerializationContext context) : 
                base(context, (MsgPack.Serialization.SerializerCapabilities.PackTo | MsgPack.Serialization.SerializerCapabilities.UnpackFrom)) {
            MsgPack.Serialization.PolymorphismSchema schema0 = default(MsgPack.Serialization.PolymorphismSchema);
            schema0 = null;
            this._serializer0 = context.GetSerializer<SystemModels.Message>(schema0);
            MsgPack.Serialization.PolymorphismSchema schema1 = default(MsgPack.Serialization.PolymorphismSchema);
            schema1 = MsgPack.Serialization.PolymorphismSchema.ForPolymorphicObject(typeof(DT.MdmMetadata.CoreEntity.InitialMessageProperty));
            this._serializer1 = context.GetSerializer<DT.MdmMetadata.CoreEntity.InitialMessageProperty>(schema1);
            MsgPack.Serialization.PolymorphismSchema schema2 = default(MsgPack.Serialization.PolymorphismSchema);
            schema2 = null;
            this._serializer2 = context.GetSerializer<SystemModels.ТипДанныхФайл>(schema2);
            this._fieldFile2File___core_ТипДанныхФайл0 = MsgPack.Serialization.ReflectionHelpers.GetField(typeof(SystemModels.SystemModel.File2File), "__core_ТипДанныхФайл");
            this._methodBaseBaseScope_set_InitMessage0 = MsgPack.Serialization.ReflectionHelpers.GetMethod(typeof(SystemModels.BaseScope), "set_InitMessage", new System.Type[] {
                        typeof(SystemModels.Message)});
            this._methodBaseBaseScope_set_InitData1 = MsgPack.Serialization.ReflectionHelpers.GetMethod(typeof(SystemModels.BaseScope), "set_InitData", new System.Type[] {
                        typeof(DT.MdmMetadata.CoreEntity.InitialMessageProperty)});
            System.Action<MsgPack.Packer, SystemModels.SystemModel.File2File>[] packOperationList = default(System.Action<MsgPack.Packer, SystemModels.SystemModel.File2File>[]);
            packOperationList = new System.Action<MsgPack.Packer, SystemModels.SystemModel.File2File>[3];
            packOperationList[0] = new System.Action<MsgPack.Packer, SystemModels.SystemModel.File2File>(this.PackValueOfInitMessage);
            packOperationList[1] = new System.Action<MsgPack.Packer, SystemModels.SystemModel.File2File>(this.PackValueOfInitData);
            packOperationList[2] = new System.Action<MsgPack.Packer, SystemModels.SystemModel.File2File>(this.PackValueOf__core_ТипДанныхФайл);
            this._packOperationList = packOperationList;
            System.Collections.Generic.Dictionary<string, System.Action<MsgPack.Packer, SystemModels.SystemModel.File2File>> packOperationTable = default(System.Collections.Generic.Dictionary<string, System.Action<MsgPack.Packer, SystemModels.SystemModel.File2File>>);
            packOperationTable = new System.Collections.Generic.Dictionary<string, System.Action<MsgPack.Packer, SystemModels.SystemModel.File2File>>(3);
            packOperationTable["InitMessage"] = new System.Action<MsgPack.Packer, SystemModels.SystemModel.File2File>(this.PackValueOfInitMessage);
            packOperationTable["InitData"] = new System.Action<MsgPack.Packer, SystemModels.SystemModel.File2File>(this.PackValueOfInitData);
            packOperationTable["__core_ТипДанныхФайл"] = new System.Action<MsgPack.Packer, SystemModels.SystemModel.File2File>(this.PackValueOf__core_ТипДанныхФайл);
            this._packOperationTable = packOperationTable;
            System.Collections.Generic.Dictionary<string, System.Func<SystemModels.SystemModel.File2File, bool>> nullCheckerTable = default(System.Collections.Generic.Dictionary<string, System.Func<SystemModels.SystemModel.File2File, bool>>);
            nullCheckerTable = new System.Collections.Generic.Dictionary<string, System.Func<SystemModels.SystemModel.File2File, bool>>(3);
            nullCheckerTable["InitMessage"] = new System.Func<SystemModels.SystemModel.File2File, bool>(this.IsInitMessageNull);
            nullCheckerTable["InitData"] = new System.Func<SystemModels.SystemModel.File2File, bool>(this.IsInitDataNull);
            nullCheckerTable["__core_ТипДанныхФайл"] = new System.Func<SystemModels.SystemModel.File2File, bool>(this.Is__core_ТипДанныхФайлNull);
            this._nullCheckersTable = nullCheckerTable;
            System.Action<MsgPack.Unpacker, SystemModels.SystemModel.File2File, int, int>[] unpackOperationList = default(System.Action<MsgPack.Unpacker, SystemModels.SystemModel.File2File, int, int>[]);
            unpackOperationList = new System.Action<MsgPack.Unpacker, SystemModels.SystemModel.File2File, int, int>[3];
            unpackOperationList[0] = new System.Action<MsgPack.Unpacker, SystemModels.SystemModel.File2File, int, int>(this.UnpackValueOfInitMessage);
            unpackOperationList[1] = new System.Action<MsgPack.Unpacker, SystemModels.SystemModel.File2File, int, int>(this.UnpackValueOfInitData);
            unpackOperationList[2] = new System.Action<MsgPack.Unpacker, SystemModels.SystemModel.File2File, int, int>(this.UnpackValueOf__core_ТипДанныхФайл);
            this._unpackOperationList = unpackOperationList;
            System.Collections.Generic.Dictionary<string, System.Action<MsgPack.Unpacker, SystemModels.SystemModel.File2File, int, int>> unpackOperationTable = default(System.Collections.Generic.Dictionary<string, System.Action<MsgPack.Unpacker, SystemModels.SystemModel.File2File, int, int>>);
            unpackOperationTable = new System.Collections.Generic.Dictionary<string, System.Action<MsgPack.Unpacker, SystemModels.SystemModel.File2File, int, int>>(3);
            unpackOperationTable["InitMessage"] = new System.Action<MsgPack.Unpacker, SystemModels.SystemModel.File2File, int, int>(this.UnpackValueOfInitMessage);
            unpackOperationTable["InitData"] = new System.Action<MsgPack.Unpacker, SystemModels.SystemModel.File2File, int, int>(this.UnpackValueOfInitData);
            unpackOperationTable["__core_ТипДанныхФайл"] = new System.Action<MsgPack.Unpacker, SystemModels.SystemModel.File2File, int, int>(this.UnpackValueOf__core_ТипДанныхФайл);
            this._unpackOperationTable = unpackOperationTable;
            this._memberNames = new string[] {
                    "InitMessage",
                    "InitData",
                    "__core_ТипДанныхФайл"};
            this.this_SetUnpackedValueOfInitMessageDelegate = new System.Action<SystemModels.SystemModel.File2File, SystemModels.Message>(this.SetUnpackedValueOfInitMessage);
            this.this_SetUnpackedValueOfInitDataDelegate = new System.Action<SystemModels.SystemModel.File2File, DT.MdmMetadata.CoreEntity.InitialMessageProperty>(this.SetUnpackedValueOfInitData);
            this.this_SetUnpackedValueOf__core_ТипДанныхФайлDelegate = new System.Action<SystemModels.SystemModel.File2File, SystemModels.ТипДанныхФайл>(this.SetUnpackedValueOf__core_ТипДанныхФайл);
        }
        
        private void PackValueOfInitMessage(MsgPack.Packer packer, SystemModels.SystemModel.File2File objectTree) {
            this._serializer0.PackTo(packer, objectTree.InitMessage);
        }
        
        private bool IsInitMessageNull(SystemModels.SystemModel.File2File objectTree) {
            return (objectTree.InitMessage == null);
        }
        
        private void PackValueOfInitData(MsgPack.Packer packer, SystemModels.SystemModel.File2File objectTree) {
            this._serializer1.PackTo(packer, objectTree.InitData);
        }
        
        private bool IsInitDataNull(SystemModels.SystemModel.File2File objectTree) {
            return (objectTree.InitData == null);
        }
        
        private void PackValueOf__core_ТипДанныхФайл(MsgPack.Packer packer, SystemModels.SystemModel.File2File objectTree) {
            this._serializer2.PackTo(packer, ((SystemModels.ТипДанныхФайл)(this._fieldFile2File___core_ТипДанныхФайл0.GetValue(objectTree))));
        }
        
        private bool Is__core_ТипДанныхФайлNull(SystemModels.SystemModel.File2File objectTree) {
            return (((SystemModels.ТипДанныхФайл)(this._fieldFile2File___core_ТипДанныхФайл0.GetValue(objectTree))) == null);
        }
        
        protected override void PackToCore(MsgPack.Packer packer, SystemModels.SystemModel.File2File objectTree) {
            MsgPack.Serialization.PackToArrayParameters<SystemModels.SystemModel.File2File> packHelperParameters = default(MsgPack.Serialization.PackToArrayParameters<SystemModels.SystemModel.File2File>);
            packHelperParameters.Packer = packer;
            packHelperParameters.Target = objectTree;
            packHelperParameters.Operations = this._packOperationList;
            MsgPack.Serialization.PackToMapParameters<SystemModels.SystemModel.File2File> packHelperParameters0 = default(MsgPack.Serialization.PackToMapParameters<SystemModels.SystemModel.File2File>);
            packHelperParameters0.Packer = packer;
            packHelperParameters0.Target = objectTree;
            packHelperParameters0.Operations = this._packOperationTable;
            packHelperParameters0.SerializationContext = this.OwnerContext;
            packHelperParameters0.NullCheckers = this._nullCheckersTable;
            if ((this.OwnerContext.SerializationMethod == MsgPack.Serialization.SerializationMethod.Array)) {
                MsgPack.Serialization.PackHelpers.PackToArray(ref packHelperParameters);
            }
            else {
                MsgPack.Serialization.PackHelpers.PackToMap(ref packHelperParameters0);
            }
        }
        
        private void SetUnpackedValueOfInitMessage(SystemModels.SystemModel.File2File unpackingContext, SystemModels.Message unpackedValue) {
            this._methodBaseBaseScope_set_InitMessage0.Invoke(unpackingContext, new object[] {
                        unpackedValue});
        }
        
        private void UnpackValueOfInitMessage(MsgPack.Unpacker unpacker, SystemModels.SystemModel.File2File unpackingContext, int indexOfItem, int itemsCount) {
            MsgPack.Serialization.UnpackReferenceTypeValueParameters<SystemModels.SystemModel.File2File, SystemModels.Message> unpackHelperParameters = default(MsgPack.Serialization.UnpackReferenceTypeValueParameters<SystemModels.SystemModel.File2File, SystemModels.Message>);
            unpackHelperParameters.Unpacker = unpacker;
            unpackHelperParameters.UnpackingContext = unpackingContext;
            unpackHelperParameters.Serializer = this._serializer0;
            unpackHelperParameters.ItemsCount = itemsCount;
            unpackHelperParameters.Unpacked = indexOfItem;
            unpackHelperParameters.TargetObjectType = typeof(SystemModels.Message);
            unpackHelperParameters.MemberName = "InitMessage";
            unpackHelperParameters.NilImplication = MsgPack.Serialization.NilImplication.MemberDefault;
            unpackHelperParameters.DirectRead = null;
            unpackHelperParameters.Setter = this.this_SetUnpackedValueOfInitMessageDelegate;
            MsgPack.Serialization.UnpackHelpers.UnpackReferenceTypeValue(ref unpackHelperParameters);
        }
        
        private void SetUnpackedValueOfInitData(SystemModels.SystemModel.File2File unpackingContext, DT.MdmMetadata.CoreEntity.InitialMessageProperty unpackedValue) {
            this._methodBaseBaseScope_set_InitData1.Invoke(unpackingContext, new object[] {
                        unpackedValue});
        }
        
        private void UnpackValueOfInitData(MsgPack.Unpacker unpacker, SystemModels.SystemModel.File2File unpackingContext, int indexOfItem, int itemsCount) {
            MsgPack.Serialization.UnpackReferenceTypeValueParameters<SystemModels.SystemModel.File2File, DT.MdmMetadata.CoreEntity.InitialMessageProperty> unpackHelperParameters0 = default(MsgPack.Serialization.UnpackReferenceTypeValueParameters<SystemModels.SystemModel.File2File, DT.MdmMetadata.CoreEntity.InitialMessageProperty>);
            unpackHelperParameters0.Unpacker = unpacker;
            unpackHelperParameters0.UnpackingContext = unpackingContext;
            unpackHelperParameters0.Serializer = this._serializer1;
            unpackHelperParameters0.ItemsCount = itemsCount;
            unpackHelperParameters0.Unpacked = indexOfItem;
            unpackHelperParameters0.TargetObjectType = typeof(DT.MdmMetadata.CoreEntity.InitialMessageProperty);
            unpackHelperParameters0.MemberName = "InitData";
            unpackHelperParameters0.NilImplication = MsgPack.Serialization.NilImplication.MemberDefault;
            unpackHelperParameters0.DirectRead = null;
            unpackHelperParameters0.Setter = this.this_SetUnpackedValueOfInitDataDelegate;
            MsgPack.Serialization.UnpackHelpers.UnpackReferenceTypeValue(ref unpackHelperParameters0);
        }
        
        private void SetUnpackedValueOf__core_ТипДанныхФайл(SystemModels.SystemModel.File2File unpackingContext, SystemModels.ТипДанныхФайл unpackedValue) {
            this._fieldFile2File___core_ТипДанныхФайл0.SetValue(unpackingContext, unpackedValue);
        }
        
        private void UnpackValueOf__core_ТипДанныхФайл(MsgPack.Unpacker unpacker, SystemModels.SystemModel.File2File unpackingContext, int indexOfItem, int itemsCount) {
            MsgPack.Serialization.UnpackReferenceTypeValueParameters<SystemModels.SystemModel.File2File, SystemModels.ТипДанныхФайл> unpackHelperParameters1 = default(MsgPack.Serialization.UnpackReferenceTypeValueParameters<SystemModels.SystemModel.File2File, SystemModels.ТипДанныхФайл>);
            unpackHelperParameters1.Unpacker = unpacker;
            unpackHelperParameters1.UnpackingContext = unpackingContext;
            unpackHelperParameters1.Serializer = this._serializer2;
            unpackHelperParameters1.ItemsCount = itemsCount;
            unpackHelperParameters1.Unpacked = indexOfItem;
            unpackHelperParameters1.TargetObjectType = typeof(SystemModels.ТипДанныхФайл);
            unpackHelperParameters1.MemberName = "__core_ТипДанныхФайл";
            unpackHelperParameters1.NilImplication = MsgPack.Serialization.NilImplication.MemberDefault;
            unpackHelperParameters1.DirectRead = null;
            unpackHelperParameters1.Setter = this.this_SetUnpackedValueOf__core_ТипДанныхФайлDelegate;
            MsgPack.Serialization.UnpackHelpers.UnpackReferenceTypeValue(ref unpackHelperParameters1);
        }
        
        protected override SystemModels.SystemModel.File2File UnpackFromCore(MsgPack.Unpacker unpacker) {
            SystemModels.SystemModel.File2File result = default(SystemModels.SystemModel.File2File);
            result = new SystemModels.SystemModel.File2File();
            if (unpacker.IsArrayHeader) {
                return MsgPack.Serialization.UnpackHelpers.UnpackFromArray(unpacker, result, MsgPack.Serialization.UnpackHelpers.GetIdentity<SystemModels.SystemModel.File2File>(), this._memberNames, this._unpackOperationList);
            }
            else {
                return MsgPack.Serialization.UnpackHelpers.UnpackFromMap(unpacker, result, MsgPack.Serialization.UnpackHelpers.GetIdentity<SystemModels.SystemModel.File2File>(), this._unpackOperationTable);
            }
        }
    }
}

