//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SystemModels {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("MsgPack.Serialization.CodeDomSerializers.CodeDomSerializerBuilder", "1.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public class SystemModels_ТипДанныхФайлSerializer : MsgPack.Serialization.MessagePackSerializer<SystemModels.ТипДанныхФайл> {
        
        private System.Reflection.FieldInfo _fieldBaseClass__msgPackDummyField0;
        
        private MsgPack.Serialization.MessagePackSerializer<byte> _serializer0;
        
        private System.Reflection.FieldInfo _fieldТипДанныхФайл___core_testField11;
        
        private MsgPack.Serialization.MessagePackSerializer<string> _serializer1;
        
        private System.Reflection.FieldInfo _fieldТипДанныхФайл___core_testField22;
        
        private System.Collections.Generic.IList<System.Action<MsgPack.Packer, SystemModels.ТипДанныхФайл>> _packOperationList;
        
        private System.Collections.Generic.IDictionary<string, System.Action<MsgPack.Packer, SystemModels.ТипДанныхФайл>> _packOperationTable;
        
        private System.Collections.Generic.IDictionary<string, System.Func<SystemModels.ТипДанныхФайл, bool>> _nullCheckersTable;
        
        private System.Action<SystemModels.ТипДанныхФайл, byte> this_SetUnpackedValueOf_msgPackDummyFieldDelegate;
        
        private System.Func<MsgPack.Unpacker, System.Type, string, byte> MsgPack_Serialization_UnpackHelpers_UnpackByteValueDelegate;
        
        private System.Action<SystemModels.ТипДанныхФайл, string> this_SetUnpackedValueOf__core_testField1Delegate;
        
        private System.Func<MsgPack.Unpacker, System.Type, string, string> MsgPack_Serialization_UnpackHelpers_UnpackStringValueDelegate;
        
        private System.Action<SystemModels.ТипДанныхФайл, string> this_SetUnpackedValueOf__core_testField2Delegate;
        
        private System.Collections.Generic.IList<string> _memberNames;
        
        private System.Collections.Generic.IList<System.Action<MsgPack.Unpacker, SystemModels.ТипДанныхФайл, int, int>> _unpackOperationList;
        
        private System.Collections.Generic.IDictionary<string, System.Action<MsgPack.Unpacker, SystemModels.ТипДанныхФайл, int, int>> _unpackOperationTable;
        
        public SystemModels_ТипДанныхФайлSerializer(MsgPack.Serialization.SerializationContext context) : 
                base(context, (MsgPack.Serialization.SerializerCapabilities.PackTo | MsgPack.Serialization.SerializerCapabilities.UnpackFrom)) {
            MsgPack.Serialization.PolymorphismSchema schema0 = default(MsgPack.Serialization.PolymorphismSchema);
            schema0 = null;
            this._serializer0 = context.GetSerializer<byte>(schema0);
            MsgPack.Serialization.PolymorphismSchema schema1 = default(MsgPack.Serialization.PolymorphismSchema);
            schema1 = null;
            this._serializer1 = context.GetSerializer<string>(schema1);
            this._fieldBaseClass__msgPackDummyField0 = MsgPack.Serialization.ReflectionHelpers.GetField(typeof(SystemModels.BaseClass), "_msgPackDummyField");
            this._fieldТипДанныхФайл___core_testField11 = MsgPack.Serialization.ReflectionHelpers.GetField(typeof(SystemModels.ТипДанныхФайл), "__core_testField1");
            this._fieldТипДанныхФайл___core_testField22 = MsgPack.Serialization.ReflectionHelpers.GetField(typeof(SystemModels.ТипДанныхФайл), "__core_testField2");
            System.Action<MsgPack.Packer, SystemModels.ТипДанныхФайл>[] packOperationList = default(System.Action<MsgPack.Packer, SystemModels.ТипДанныхФайл>[]);
            packOperationList = new System.Action<MsgPack.Packer, SystemModels.ТипДанныхФайл>[3];
            packOperationList[0] = new System.Action<MsgPack.Packer, SystemModels.ТипДанныхФайл>(this.PackValueOf_msgPackDummyField);
            packOperationList[1] = new System.Action<MsgPack.Packer, SystemModels.ТипДанныхФайл>(this.PackValueOf__core_testField1);
            packOperationList[2] = new System.Action<MsgPack.Packer, SystemModels.ТипДанныхФайл>(this.PackValueOf__core_testField2);
            this._packOperationList = packOperationList;
            System.Collections.Generic.Dictionary<string, System.Action<MsgPack.Packer, SystemModels.ТипДанныхФайл>> packOperationTable = default(System.Collections.Generic.Dictionary<string, System.Action<MsgPack.Packer, SystemModels.ТипДанныхФайл>>);
            packOperationTable = new System.Collections.Generic.Dictionary<string, System.Action<MsgPack.Packer, SystemModels.ТипДанныхФайл>>(3);
            packOperationTable["_msgPackDummyField"] = new System.Action<MsgPack.Packer, SystemModels.ТипДанныхФайл>(this.PackValueOf_msgPackDummyField);
            packOperationTable["__core_testField1"] = new System.Action<MsgPack.Packer, SystemModels.ТипДанныхФайл>(this.PackValueOf__core_testField1);
            packOperationTable["__core_testField2"] = new System.Action<MsgPack.Packer, SystemModels.ТипДанныхФайл>(this.PackValueOf__core_testField2);
            this._packOperationTable = packOperationTable;
            System.Collections.Generic.Dictionary<string, System.Func<SystemModels.ТипДанныхФайл, bool>> nullCheckerTable = default(System.Collections.Generic.Dictionary<string, System.Func<SystemModels.ТипДанныхФайл, bool>>);
            nullCheckerTable = new System.Collections.Generic.Dictionary<string, System.Func<SystemModels.ТипДанныхФайл, bool>>(2);
            nullCheckerTable["__core_testField1"] = new System.Func<SystemModels.ТипДанныхФайл, bool>(this.Is__core_testField1Null);
            nullCheckerTable["__core_testField2"] = new System.Func<SystemModels.ТипДанныхФайл, bool>(this.Is__core_testField2Null);
            this._nullCheckersTable = nullCheckerTable;
            System.Action<MsgPack.Unpacker, SystemModels.ТипДанныхФайл, int, int>[] unpackOperationList = default(System.Action<MsgPack.Unpacker, SystemModels.ТипДанныхФайл, int, int>[]);
            unpackOperationList = new System.Action<MsgPack.Unpacker, SystemModels.ТипДанныхФайл, int, int>[3];
            unpackOperationList[0] = new System.Action<MsgPack.Unpacker, SystemModels.ТипДанныхФайл, int, int>(this.UnpackValueOf_msgPackDummyField);
            unpackOperationList[1] = new System.Action<MsgPack.Unpacker, SystemModels.ТипДанныхФайл, int, int>(this.UnpackValueOf__core_testField1);
            unpackOperationList[2] = new System.Action<MsgPack.Unpacker, SystemModels.ТипДанныхФайл, int, int>(this.UnpackValueOf__core_testField2);
            this._unpackOperationList = unpackOperationList;
            System.Collections.Generic.Dictionary<string, System.Action<MsgPack.Unpacker, SystemModels.ТипДанныхФайл, int, int>> unpackOperationTable = default(System.Collections.Generic.Dictionary<string, System.Action<MsgPack.Unpacker, SystemModels.ТипДанныхФайл, int, int>>);
            unpackOperationTable = new System.Collections.Generic.Dictionary<string, System.Action<MsgPack.Unpacker, SystemModels.ТипДанныхФайл, int, int>>(3);
            unpackOperationTable["_msgPackDummyField"] = new System.Action<MsgPack.Unpacker, SystemModels.ТипДанныхФайл, int, int>(this.UnpackValueOf_msgPackDummyField);
            unpackOperationTable["__core_testField1"] = new System.Action<MsgPack.Unpacker, SystemModels.ТипДанныхФайл, int, int>(this.UnpackValueOf__core_testField1);
            unpackOperationTable["__core_testField2"] = new System.Action<MsgPack.Unpacker, SystemModels.ТипДанныхФайл, int, int>(this.UnpackValueOf__core_testField2);
            this._unpackOperationTable = unpackOperationTable;
            this._memberNames = new string[] {
                    "_msgPackDummyField",
                    "__core_testField1",
                    "__core_testField2"};
            this.this_SetUnpackedValueOf_msgPackDummyFieldDelegate = new System.Action<SystemModels.ТипДанныхФайл, byte>(this.SetUnpackedValueOf_msgPackDummyField);
            this.MsgPack_Serialization_UnpackHelpers_UnpackByteValueDelegate = new System.Func<MsgPack.Unpacker, System.Type, string, byte>(MsgPack.Serialization.UnpackHelpers.UnpackByteValue);
            this.this_SetUnpackedValueOf__core_testField1Delegate = new System.Action<SystemModels.ТипДанныхФайл, string>(this.SetUnpackedValueOf__core_testField1);
            this.MsgPack_Serialization_UnpackHelpers_UnpackStringValueDelegate = new System.Func<MsgPack.Unpacker, System.Type, string, string>(MsgPack.Serialization.UnpackHelpers.UnpackStringValue);
            this.this_SetUnpackedValueOf__core_testField2Delegate = new System.Action<SystemModels.ТипДанныхФайл, string>(this.SetUnpackedValueOf__core_testField2);
        }
        
        private void PackValueOf_msgPackDummyField(MsgPack.Packer packer, SystemModels.ТипДанныхФайл objectTree) {
            this._serializer0.PackTo(packer, ((byte)(this._fieldBaseClass__msgPackDummyField0.GetValue(objectTree))));
        }
        
        private void PackValueOf__core_testField1(MsgPack.Packer packer, SystemModels.ТипДанныхФайл objectTree) {
            this._serializer1.PackTo(packer, ((string)(this._fieldТипДанныхФайл___core_testField11.GetValue(objectTree))));
        }
        
        private bool Is__core_testField1Null(SystemModels.ТипДанныхФайл objectTree) {
            return (((string)(this._fieldТипДанныхФайл___core_testField11.GetValue(objectTree))) == null);
        }
        
        private void PackValueOf__core_testField2(MsgPack.Packer packer, SystemModels.ТипДанныхФайл objectTree) {
            this._serializer1.PackTo(packer, ((string)(this._fieldТипДанныхФайл___core_testField22.GetValue(objectTree))));
        }
        
        private bool Is__core_testField2Null(SystemModels.ТипДанныхФайл objectTree) {
            return (((string)(this._fieldТипДанныхФайл___core_testField22.GetValue(objectTree))) == null);
        }
        
        protected override void PackToCore(MsgPack.Packer packer, SystemModels.ТипДанныхФайл objectTree) {
            MsgPack.Serialization.PackToArrayParameters<SystemModels.ТипДанныхФайл> packHelperParameters = default(MsgPack.Serialization.PackToArrayParameters<SystemModels.ТипДанныхФайл>);
            packHelperParameters.Packer = packer;
            packHelperParameters.Target = objectTree;
            packHelperParameters.Operations = this._packOperationList;
            MsgPack.Serialization.PackToMapParameters<SystemModels.ТипДанныхФайл> packHelperParameters0 = default(MsgPack.Serialization.PackToMapParameters<SystemModels.ТипДанныхФайл>);
            packHelperParameters0.Packer = packer;
            packHelperParameters0.Target = objectTree;
            packHelperParameters0.Operations = this._packOperationTable;
            packHelperParameters0.SerializationContext = this.OwnerContext;
            packHelperParameters0.NullCheckers = this._nullCheckersTable;
            if ((this.OwnerContext.SerializationMethod == MsgPack.Serialization.SerializationMethod.Array)) {
                MsgPack.Serialization.PackHelpers.PackToArray(ref packHelperParameters);
            }
            else {
                MsgPack.Serialization.PackHelpers.PackToMap(ref packHelperParameters0);
            }
        }
        
        private void SetUnpackedValueOf_msgPackDummyField(SystemModels.ТипДанныхФайл unpackingContext, byte unpackedValue) {
            this._fieldBaseClass__msgPackDummyField0.SetValue(unpackingContext, ((object)(unpackedValue)));
        }
        
        private void UnpackValueOf_msgPackDummyField(MsgPack.Unpacker unpacker, SystemModels.ТипДанныхФайл unpackingContext, int indexOfItem, int itemsCount) {
            MsgPack.Serialization.UnpackValueTypeValueParameters<SystemModels.ТипДанныхФайл, byte> unpackHelperParameters = default(MsgPack.Serialization.UnpackValueTypeValueParameters<SystemModels.ТипДанныхФайл, byte>);
            unpackHelperParameters.Unpacker = unpacker;
            unpackHelperParameters.UnpackingContext = unpackingContext;
            unpackHelperParameters.Serializer = this._serializer0;
            unpackHelperParameters.ItemsCount = itemsCount;
            unpackHelperParameters.Unpacked = indexOfItem;
            unpackHelperParameters.TargetObjectType = typeof(byte);
            unpackHelperParameters.MemberName = "_msgPackDummyField";
            unpackHelperParameters.DirectRead = this.MsgPack_Serialization_UnpackHelpers_UnpackByteValueDelegate;
            unpackHelperParameters.Setter = this.this_SetUnpackedValueOf_msgPackDummyFieldDelegate;
            MsgPack.Serialization.UnpackHelpers.UnpackValueTypeValue(ref unpackHelperParameters);
        }
        
        private void SetUnpackedValueOf__core_testField1(SystemModels.ТипДанныхФайл unpackingContext, string unpackedValue) {
            this._fieldТипДанныхФайл___core_testField11.SetValue(unpackingContext, unpackedValue);
        }
        
        private void UnpackValueOf__core_testField1(MsgPack.Unpacker unpacker, SystemModels.ТипДанныхФайл unpackingContext, int indexOfItem, int itemsCount) {
            MsgPack.Serialization.UnpackReferenceTypeValueParameters<SystemModels.ТипДанныхФайл, string> unpackHelperParameters0 = default(MsgPack.Serialization.UnpackReferenceTypeValueParameters<SystemModels.ТипДанныхФайл, string>);
            unpackHelperParameters0.Unpacker = unpacker;
            unpackHelperParameters0.UnpackingContext = unpackingContext;
            unpackHelperParameters0.Serializer = this._serializer1;
            unpackHelperParameters0.ItemsCount = itemsCount;
            unpackHelperParameters0.Unpacked = indexOfItem;
            unpackHelperParameters0.TargetObjectType = typeof(string);
            unpackHelperParameters0.MemberName = "__core_testField1";
            unpackHelperParameters0.NilImplication = MsgPack.Serialization.NilImplication.MemberDefault;
            unpackHelperParameters0.DirectRead = this.MsgPack_Serialization_UnpackHelpers_UnpackStringValueDelegate;
            unpackHelperParameters0.Setter = this.this_SetUnpackedValueOf__core_testField1Delegate;
            MsgPack.Serialization.UnpackHelpers.UnpackReferenceTypeValue(ref unpackHelperParameters0);
        }
        
        private void SetUnpackedValueOf__core_testField2(SystemModels.ТипДанныхФайл unpackingContext, string unpackedValue) {
            this._fieldТипДанныхФайл___core_testField22.SetValue(unpackingContext, unpackedValue);
        }
        
        private void UnpackValueOf__core_testField2(MsgPack.Unpacker unpacker, SystemModels.ТипДанныхФайл unpackingContext, int indexOfItem, int itemsCount) {
            MsgPack.Serialization.UnpackReferenceTypeValueParameters<SystemModels.ТипДанныхФайл, string> unpackHelperParameters1 = default(MsgPack.Serialization.UnpackReferenceTypeValueParameters<SystemModels.ТипДанныхФайл, string>);
            unpackHelperParameters1.Unpacker = unpacker;
            unpackHelperParameters1.UnpackingContext = unpackingContext;
            unpackHelperParameters1.Serializer = this._serializer1;
            unpackHelperParameters1.ItemsCount = itemsCount;
            unpackHelperParameters1.Unpacked = indexOfItem;
            unpackHelperParameters1.TargetObjectType = typeof(string);
            unpackHelperParameters1.MemberName = "__core_testField2";
            unpackHelperParameters1.NilImplication = MsgPack.Serialization.NilImplication.MemberDefault;
            unpackHelperParameters1.DirectRead = this.MsgPack_Serialization_UnpackHelpers_UnpackStringValueDelegate;
            unpackHelperParameters1.Setter = this.this_SetUnpackedValueOf__core_testField2Delegate;
            MsgPack.Serialization.UnpackHelpers.UnpackReferenceTypeValue(ref unpackHelperParameters1);
        }
        
        protected override SystemModels.ТипДанныхФайл UnpackFromCore(MsgPack.Unpacker unpacker) {
            SystemModels.ТипДанныхФайл result = default(SystemModels.ТипДанныхФайл);
            result = new SystemModels.ТипДанныхФайл();
            if (unpacker.IsArrayHeader) {
                return MsgPack.Serialization.UnpackHelpers.UnpackFromArray(unpacker, result, MsgPack.Serialization.UnpackHelpers.GetIdentity<SystemModels.ТипДанныхФайл>(), this._memberNames, this._unpackOperationList);
            }
            else {
                return MsgPack.Serialization.UnpackHelpers.UnpackFromMap(unpacker, result, MsgPack.Serialization.UnpackHelpers.GetIdentity<SystemModels.ТипДанныхФайл>(), this._unpackOperationTable);
            }
        }
    }
}

