//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SystemModels {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("MsgPack.Serialization.CodeDomSerializers.CodeDomSerializerBuilder", "1.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public class Metadata_HandlerInfoSerializer : MsgPack.Serialization.MessagePackSerializer<Metadata.HandlerInfo> {
        
        private MsgPack.Serialization.MessagePackSerializer<Metadata.ConnectorType> _serializer0;
        
        private MsgPack.Serialization.MessagePackSerializer<string> _serializer1;
        
        private MsgPack.Serialization.MessagePackSerializer<System.Guid> _serializer2;
        
        private MsgPack.Serialization.MessagePackSerializer<SystemModels.PropertiesCollection> _serializer3;
        
        private MsgPack.Serialization.MessagePackSerializer<bool> _serializer4;
        
        private MsgPack.Serialization.MessagePackSerializer<Metadata.DataTypes> _serializer5;
        
        private MsgPack.Serialization.MessagePackSerializer<Metadata.SM> _serializer6;
        
        private System.Collections.Generic.IList<System.Action<MsgPack.Packer, Metadata.HandlerInfo>> _packOperationList;
        
        private System.Collections.Generic.IDictionary<string, System.Action<MsgPack.Packer, Metadata.HandlerInfo>> _packOperationTable;
        
        private System.Collections.Generic.IDictionary<string, System.Func<Metadata.HandlerInfo, bool>> _nullCheckersTable;
        
        private System.Action<Metadata.HandlerInfo, Metadata.ConnectorType> this_SetUnpackedValueOfConnectorTypeDelegate;
        
        private System.Action<Metadata.HandlerInfo, string> this_SetUnpackedValueOfDescriptionDelegate;
        
        private System.Func<MsgPack.Unpacker, System.Type, string, string> MsgPack_Serialization_UnpackHelpers_UnpackStringValueDelegate;
        
        private System.Action<Metadata.HandlerInfo, System.Guid> this_SetUnpackedValueOfIdDelegate;
        
        private System.Action<Metadata.HandlerInfo, string> this_SetUnpackedValueOfNameDelegate;
        
        private System.Action<Metadata.HandlerInfo, SystemModels.PropertiesCollection> this_SetUnpackedValueOfParametersDelegate;
        
        private System.Action<Metadata.HandlerInfo, bool> this_SetUnpackedValueOfWaitArrayDelegate;
        
        private System.Func<MsgPack.Unpacker, System.Type, string, bool> MsgPack_Serialization_UnpackHelpers_UnpackBooleanValueDelegate;
        
        private System.Action<Metadata.HandlerInfo, Metadata.DataTypes> this_SetUnpackedValueOfWaitDataTypeDelegate;
        
        private System.Action<Metadata.HandlerInfo, bool> this_SetUnpackedValueOfWaitResponseDelegate;
        
        private System.Action<Metadata.HandlerInfo, Metadata.SM> this_SetUnpackedValueOfWaitSystemDataTypeDelegate;
        
        private System.Collections.Generic.IList<string> _memberNames;
        
        private System.Collections.Generic.IList<System.Action<MsgPack.Unpacker, Metadata.HandlerInfo, int, int>> _unpackOperationList;
        
        private System.Collections.Generic.IDictionary<string, System.Action<MsgPack.Unpacker, Metadata.HandlerInfo, int, int>> _unpackOperationTable;
        
        public Metadata_HandlerInfoSerializer(MsgPack.Serialization.SerializationContext context) : 
                base(context, (MsgPack.Serialization.SerializerCapabilities.PackTo | MsgPack.Serialization.SerializerCapabilities.UnpackFrom)) {
            this._serializer0 = context.GetSerializer<Metadata.ConnectorType>(MsgPack.Serialization.EnumMessagePackSerializerHelpers.DetermineEnumSerializationMethod(context, typeof(Metadata.ConnectorType), MsgPack.Serialization.EnumMemberSerializationMethod.Default));
            MsgPack.Serialization.PolymorphismSchema schema0 = default(MsgPack.Serialization.PolymorphismSchema);
            schema0 = null;
            this._serializer1 = context.GetSerializer<string>(schema0);
            MsgPack.Serialization.PolymorphismSchema schema1 = default(MsgPack.Serialization.PolymorphismSchema);
            schema1 = null;
            this._serializer2 = context.GetSerializer<System.Guid>(schema1);
            MsgPack.Serialization.PolymorphismSchema schema2 = default(MsgPack.Serialization.PolymorphismSchema);
            schema2 = null;
            this._serializer3 = context.GetSerializer<SystemModels.PropertiesCollection>(schema2);
            MsgPack.Serialization.PolymorphismSchema schema3 = default(MsgPack.Serialization.PolymorphismSchema);
            schema3 = null;
            this._serializer4 = context.GetSerializer<bool>(schema3);
            this._serializer5 = context.GetSerializer<Metadata.DataTypes>(MsgPack.Serialization.EnumMessagePackSerializerHelpers.DetermineEnumSerializationMethod(context, typeof(Metadata.DataTypes), MsgPack.Serialization.EnumMemberSerializationMethod.Default));
            this._serializer6 = context.GetSerializer<Metadata.SM>(MsgPack.Serialization.EnumMessagePackSerializerHelpers.DetermineEnumSerializationMethod(context, typeof(Metadata.SM), MsgPack.Serialization.EnumMemberSerializationMethod.Default));
            System.Action<MsgPack.Packer, Metadata.HandlerInfo>[] packOperationList = default(System.Action<MsgPack.Packer, Metadata.HandlerInfo>[]);
            packOperationList = new System.Action<MsgPack.Packer, Metadata.HandlerInfo>[9];
            packOperationList[0] = new System.Action<MsgPack.Packer, Metadata.HandlerInfo>(this.PackValueOfConnectorType);
            packOperationList[1] = new System.Action<MsgPack.Packer, Metadata.HandlerInfo>(this.PackValueOfDescription);
            packOperationList[2] = new System.Action<MsgPack.Packer, Metadata.HandlerInfo>(this.PackValueOfId);
            packOperationList[3] = new System.Action<MsgPack.Packer, Metadata.HandlerInfo>(this.PackValueOfName);
            packOperationList[4] = new System.Action<MsgPack.Packer, Metadata.HandlerInfo>(this.PackValueOfParameters);
            packOperationList[5] = new System.Action<MsgPack.Packer, Metadata.HandlerInfo>(this.PackValueOfWaitArray);
            packOperationList[6] = new System.Action<MsgPack.Packer, Metadata.HandlerInfo>(this.PackValueOfWaitDataType);
            packOperationList[7] = new System.Action<MsgPack.Packer, Metadata.HandlerInfo>(this.PackValueOfWaitResponse);
            packOperationList[8] = new System.Action<MsgPack.Packer, Metadata.HandlerInfo>(this.PackValueOfWaitSystemDataType);
            this._packOperationList = packOperationList;
            System.Collections.Generic.Dictionary<string, System.Action<MsgPack.Packer, Metadata.HandlerInfo>> packOperationTable = default(System.Collections.Generic.Dictionary<string, System.Action<MsgPack.Packer, Metadata.HandlerInfo>>);
            packOperationTable = new System.Collections.Generic.Dictionary<string, System.Action<MsgPack.Packer, Metadata.HandlerInfo>>(9);
            packOperationTable["ConnectorType"] = new System.Action<MsgPack.Packer, Metadata.HandlerInfo>(this.PackValueOfConnectorType);
            packOperationTable["Description"] = new System.Action<MsgPack.Packer, Metadata.HandlerInfo>(this.PackValueOfDescription);
            packOperationTable["Id"] = new System.Action<MsgPack.Packer, Metadata.HandlerInfo>(this.PackValueOfId);
            packOperationTable["Name"] = new System.Action<MsgPack.Packer, Metadata.HandlerInfo>(this.PackValueOfName);
            packOperationTable["Parameters"] = new System.Action<MsgPack.Packer, Metadata.HandlerInfo>(this.PackValueOfParameters);
            packOperationTable["WaitArray"] = new System.Action<MsgPack.Packer, Metadata.HandlerInfo>(this.PackValueOfWaitArray);
            packOperationTable["WaitDataType"] = new System.Action<MsgPack.Packer, Metadata.HandlerInfo>(this.PackValueOfWaitDataType);
            packOperationTable["WaitResponse"] = new System.Action<MsgPack.Packer, Metadata.HandlerInfo>(this.PackValueOfWaitResponse);
            packOperationTable["WaitSystemDataType"] = new System.Action<MsgPack.Packer, Metadata.HandlerInfo>(this.PackValueOfWaitSystemDataType);
            this._packOperationTable = packOperationTable;
            System.Collections.Generic.Dictionary<string, System.Func<Metadata.HandlerInfo, bool>> nullCheckerTable = default(System.Collections.Generic.Dictionary<string, System.Func<Metadata.HandlerInfo, bool>>);
            nullCheckerTable = new System.Collections.Generic.Dictionary<string, System.Func<Metadata.HandlerInfo, bool>>(3);
            nullCheckerTable["Description"] = new System.Func<Metadata.HandlerInfo, bool>(this.IsDescriptionNull);
            nullCheckerTable["Name"] = new System.Func<Metadata.HandlerInfo, bool>(this.IsNameNull);
            nullCheckerTable["Parameters"] = new System.Func<Metadata.HandlerInfo, bool>(this.IsParametersNull);
            this._nullCheckersTable = nullCheckerTable;
            System.Action<MsgPack.Unpacker, Metadata.HandlerInfo, int, int>[] unpackOperationList = default(System.Action<MsgPack.Unpacker, Metadata.HandlerInfo, int, int>[]);
            unpackOperationList = new System.Action<MsgPack.Unpacker, Metadata.HandlerInfo, int, int>[9];
            unpackOperationList[0] = new System.Action<MsgPack.Unpacker, Metadata.HandlerInfo, int, int>(this.UnpackValueOfConnectorType);
            unpackOperationList[1] = new System.Action<MsgPack.Unpacker, Metadata.HandlerInfo, int, int>(this.UnpackValueOfDescription);
            unpackOperationList[2] = new System.Action<MsgPack.Unpacker, Metadata.HandlerInfo, int, int>(this.UnpackValueOfId);
            unpackOperationList[3] = new System.Action<MsgPack.Unpacker, Metadata.HandlerInfo, int, int>(this.UnpackValueOfName);
            unpackOperationList[4] = new System.Action<MsgPack.Unpacker, Metadata.HandlerInfo, int, int>(this.UnpackValueOfParameters);
            unpackOperationList[5] = new System.Action<MsgPack.Unpacker, Metadata.HandlerInfo, int, int>(this.UnpackValueOfWaitArray);
            unpackOperationList[6] = new System.Action<MsgPack.Unpacker, Metadata.HandlerInfo, int, int>(this.UnpackValueOfWaitDataType);
            unpackOperationList[7] = new System.Action<MsgPack.Unpacker, Metadata.HandlerInfo, int, int>(this.UnpackValueOfWaitResponse);
            unpackOperationList[8] = new System.Action<MsgPack.Unpacker, Metadata.HandlerInfo, int, int>(this.UnpackValueOfWaitSystemDataType);
            this._unpackOperationList = unpackOperationList;
            System.Collections.Generic.Dictionary<string, System.Action<MsgPack.Unpacker, Metadata.HandlerInfo, int, int>> unpackOperationTable = default(System.Collections.Generic.Dictionary<string, System.Action<MsgPack.Unpacker, Metadata.HandlerInfo, int, int>>);
            unpackOperationTable = new System.Collections.Generic.Dictionary<string, System.Action<MsgPack.Unpacker, Metadata.HandlerInfo, int, int>>(9);
            unpackOperationTable["ConnectorType"] = new System.Action<MsgPack.Unpacker, Metadata.HandlerInfo, int, int>(this.UnpackValueOfConnectorType);
            unpackOperationTable["Description"] = new System.Action<MsgPack.Unpacker, Metadata.HandlerInfo, int, int>(this.UnpackValueOfDescription);
            unpackOperationTable["Id"] = new System.Action<MsgPack.Unpacker, Metadata.HandlerInfo, int, int>(this.UnpackValueOfId);
            unpackOperationTable["Name"] = new System.Action<MsgPack.Unpacker, Metadata.HandlerInfo, int, int>(this.UnpackValueOfName);
            unpackOperationTable["Parameters"] = new System.Action<MsgPack.Unpacker, Metadata.HandlerInfo, int, int>(this.UnpackValueOfParameters);
            unpackOperationTable["WaitArray"] = new System.Action<MsgPack.Unpacker, Metadata.HandlerInfo, int, int>(this.UnpackValueOfWaitArray);
            unpackOperationTable["WaitDataType"] = new System.Action<MsgPack.Unpacker, Metadata.HandlerInfo, int, int>(this.UnpackValueOfWaitDataType);
            unpackOperationTable["WaitResponse"] = new System.Action<MsgPack.Unpacker, Metadata.HandlerInfo, int, int>(this.UnpackValueOfWaitResponse);
            unpackOperationTable["WaitSystemDataType"] = new System.Action<MsgPack.Unpacker, Metadata.HandlerInfo, int, int>(this.UnpackValueOfWaitSystemDataType);
            this._unpackOperationTable = unpackOperationTable;
            this._memberNames = new string[] {
                    "ConnectorType",
                    "Description",
                    "Id",
                    "Name",
                    "Parameters",
                    "WaitArray",
                    "WaitDataType",
                    "WaitResponse",
                    "WaitSystemDataType"};
            this.this_SetUnpackedValueOfConnectorTypeDelegate = new System.Action<Metadata.HandlerInfo, Metadata.ConnectorType>(this.SetUnpackedValueOfConnectorType);
            this.this_SetUnpackedValueOfDescriptionDelegate = new System.Action<Metadata.HandlerInfo, string>(this.SetUnpackedValueOfDescription);
            this.MsgPack_Serialization_UnpackHelpers_UnpackStringValueDelegate = new System.Func<MsgPack.Unpacker, System.Type, string, string>(MsgPack.Serialization.UnpackHelpers.UnpackStringValue);
            this.this_SetUnpackedValueOfIdDelegate = new System.Action<Metadata.HandlerInfo, System.Guid>(this.SetUnpackedValueOfId);
            this.this_SetUnpackedValueOfNameDelegate = new System.Action<Metadata.HandlerInfo, string>(this.SetUnpackedValueOfName);
            this.this_SetUnpackedValueOfParametersDelegate = new System.Action<Metadata.HandlerInfo, SystemModels.PropertiesCollection>(this.SetUnpackedValueOfParameters);
            this.this_SetUnpackedValueOfWaitArrayDelegate = new System.Action<Metadata.HandlerInfo, bool>(this.SetUnpackedValueOfWaitArray);
            this.MsgPack_Serialization_UnpackHelpers_UnpackBooleanValueDelegate = new System.Func<MsgPack.Unpacker, System.Type, string, bool>(MsgPack.Serialization.UnpackHelpers.UnpackBooleanValue);
            this.this_SetUnpackedValueOfWaitDataTypeDelegate = new System.Action<Metadata.HandlerInfo, Metadata.DataTypes>(this.SetUnpackedValueOfWaitDataType);
            this.this_SetUnpackedValueOfWaitResponseDelegate = new System.Action<Metadata.HandlerInfo, bool>(this.SetUnpackedValueOfWaitResponse);
            this.this_SetUnpackedValueOfWaitSystemDataTypeDelegate = new System.Action<Metadata.HandlerInfo, Metadata.SM>(this.SetUnpackedValueOfWaitSystemDataType);
        }
        
        private void PackValueOfConnectorType(MsgPack.Packer packer, Metadata.HandlerInfo objectTree) {
            this._serializer0.PackTo(packer, objectTree.ConnectorType);
        }
        
        private void PackValueOfDescription(MsgPack.Packer packer, Metadata.HandlerInfo objectTree) {
            this._serializer1.PackTo(packer, objectTree.Description);
        }
        
        private bool IsDescriptionNull(Metadata.HandlerInfo objectTree) {
            return (objectTree.Description == null);
        }
        
        private void PackValueOfId(MsgPack.Packer packer, Metadata.HandlerInfo objectTree) {
            this._serializer2.PackTo(packer, objectTree.Id);
        }
        
        private void PackValueOfName(MsgPack.Packer packer, Metadata.HandlerInfo objectTree) {
            this._serializer1.PackTo(packer, objectTree.Name);
        }
        
        private bool IsNameNull(Metadata.HandlerInfo objectTree) {
            return (objectTree.Name == null);
        }
        
        private void PackValueOfParameters(MsgPack.Packer packer, Metadata.HandlerInfo objectTree) {
            this._serializer3.PackTo(packer, objectTree.Parameters);
        }
        
        private bool IsParametersNull(Metadata.HandlerInfo objectTree) {
            return (objectTree.Parameters == null);
        }
        
        private void PackValueOfWaitArray(MsgPack.Packer packer, Metadata.HandlerInfo objectTree) {
            this._serializer4.PackTo(packer, objectTree.WaitArray);
        }
        
        private void PackValueOfWaitDataType(MsgPack.Packer packer, Metadata.HandlerInfo objectTree) {
            this._serializer5.PackTo(packer, objectTree.WaitDataType);
        }
        
        private void PackValueOfWaitResponse(MsgPack.Packer packer, Metadata.HandlerInfo objectTree) {
            this._serializer4.PackTo(packer, objectTree.WaitResponse);
        }
        
        private void PackValueOfWaitSystemDataType(MsgPack.Packer packer, Metadata.HandlerInfo objectTree) {
            this._serializer6.PackTo(packer, objectTree.WaitSystemDataType);
        }
        
        protected override void PackToCore(MsgPack.Packer packer, Metadata.HandlerInfo objectTree) {
            MsgPack.Serialization.PackToArrayParameters<Metadata.HandlerInfo> packHelperParameters = default(MsgPack.Serialization.PackToArrayParameters<Metadata.HandlerInfo>);
            packHelperParameters.Packer = packer;
            packHelperParameters.Target = objectTree;
            packHelperParameters.Operations = this._packOperationList;
            MsgPack.Serialization.PackToMapParameters<Metadata.HandlerInfo> packHelperParameters0 = default(MsgPack.Serialization.PackToMapParameters<Metadata.HandlerInfo>);
            packHelperParameters0.Packer = packer;
            packHelperParameters0.Target = objectTree;
            packHelperParameters0.Operations = this._packOperationTable;
            packHelperParameters0.SerializationContext = this.OwnerContext;
            packHelperParameters0.NullCheckers = this._nullCheckersTable;
            if ((this.OwnerContext.SerializationMethod == MsgPack.Serialization.SerializationMethod.Array)) {
                MsgPack.Serialization.PackHelpers.PackToArray(ref packHelperParameters);
            }
            else {
                MsgPack.Serialization.PackHelpers.PackToMap(ref packHelperParameters0);
            }
        }
        
        private void SetUnpackedValueOfConnectorType(Metadata.HandlerInfo unpackingContext, Metadata.ConnectorType unpackedValue) {
            unpackingContext.ConnectorType = unpackedValue;
        }
        
        private void UnpackValueOfConnectorType(MsgPack.Unpacker unpacker, Metadata.HandlerInfo unpackingContext, int indexOfItem, int itemsCount) {
            MsgPack.Serialization.UnpackValueTypeValueParameters<Metadata.HandlerInfo, Metadata.ConnectorType> unpackHelperParameters = default(MsgPack.Serialization.UnpackValueTypeValueParameters<Metadata.HandlerInfo, Metadata.ConnectorType>);
            unpackHelperParameters.Unpacker = unpacker;
            unpackHelperParameters.UnpackingContext = unpackingContext;
            unpackHelperParameters.Serializer = this._serializer0;
            unpackHelperParameters.ItemsCount = itemsCount;
            unpackHelperParameters.Unpacked = indexOfItem;
            unpackHelperParameters.TargetObjectType = typeof(Metadata.ConnectorType);
            unpackHelperParameters.MemberName = "ConnectorType";
            unpackHelperParameters.DirectRead = null;
            unpackHelperParameters.Setter = this.this_SetUnpackedValueOfConnectorTypeDelegate;
            MsgPack.Serialization.UnpackHelpers.UnpackValueTypeValue(ref unpackHelperParameters);
        }
        
        private void SetUnpackedValueOfDescription(Metadata.HandlerInfo unpackingContext, string unpackedValue) {
            unpackingContext.Description = unpackedValue;
        }
        
        private void UnpackValueOfDescription(MsgPack.Unpacker unpacker, Metadata.HandlerInfo unpackingContext, int indexOfItem, int itemsCount) {
            MsgPack.Serialization.UnpackReferenceTypeValueParameters<Metadata.HandlerInfo, string> unpackHelperParameters0 = default(MsgPack.Serialization.UnpackReferenceTypeValueParameters<Metadata.HandlerInfo, string>);
            unpackHelperParameters0.Unpacker = unpacker;
            unpackHelperParameters0.UnpackingContext = unpackingContext;
            unpackHelperParameters0.Serializer = this._serializer1;
            unpackHelperParameters0.ItemsCount = itemsCount;
            unpackHelperParameters0.Unpacked = indexOfItem;
            unpackHelperParameters0.TargetObjectType = typeof(string);
            unpackHelperParameters0.MemberName = "Description";
            unpackHelperParameters0.NilImplication = MsgPack.Serialization.NilImplication.MemberDefault;
            unpackHelperParameters0.DirectRead = this.MsgPack_Serialization_UnpackHelpers_UnpackStringValueDelegate;
            unpackHelperParameters0.Setter = this.this_SetUnpackedValueOfDescriptionDelegate;
            MsgPack.Serialization.UnpackHelpers.UnpackReferenceTypeValue(ref unpackHelperParameters0);
        }
        
        private void SetUnpackedValueOfId(Metadata.HandlerInfo unpackingContext, System.Guid unpackedValue) {
            unpackingContext.Id = unpackedValue;
        }
        
        private void UnpackValueOfId(MsgPack.Unpacker unpacker, Metadata.HandlerInfo unpackingContext, int indexOfItem, int itemsCount) {
            MsgPack.Serialization.UnpackValueTypeValueParameters<Metadata.HandlerInfo, System.Guid> unpackHelperParameters1 = default(MsgPack.Serialization.UnpackValueTypeValueParameters<Metadata.HandlerInfo, System.Guid>);
            unpackHelperParameters1.Unpacker = unpacker;
            unpackHelperParameters1.UnpackingContext = unpackingContext;
            unpackHelperParameters1.Serializer = this._serializer2;
            unpackHelperParameters1.ItemsCount = itemsCount;
            unpackHelperParameters1.Unpacked = indexOfItem;
            unpackHelperParameters1.TargetObjectType = typeof(System.Guid);
            unpackHelperParameters1.MemberName = "Id";
            unpackHelperParameters1.DirectRead = null;
            unpackHelperParameters1.Setter = this.this_SetUnpackedValueOfIdDelegate;
            MsgPack.Serialization.UnpackHelpers.UnpackValueTypeValue(ref unpackHelperParameters1);
        }
        
        private void SetUnpackedValueOfName(Metadata.HandlerInfo unpackingContext, string unpackedValue) {
            unpackingContext.Name = unpackedValue;
        }
        
        private void UnpackValueOfName(MsgPack.Unpacker unpacker, Metadata.HandlerInfo unpackingContext, int indexOfItem, int itemsCount) {
            MsgPack.Serialization.UnpackReferenceTypeValueParameters<Metadata.HandlerInfo, string> unpackHelperParameters2 = default(MsgPack.Serialization.UnpackReferenceTypeValueParameters<Metadata.HandlerInfo, string>);
            unpackHelperParameters2.Unpacker = unpacker;
            unpackHelperParameters2.UnpackingContext = unpackingContext;
            unpackHelperParameters2.Serializer = this._serializer1;
            unpackHelperParameters2.ItemsCount = itemsCount;
            unpackHelperParameters2.Unpacked = indexOfItem;
            unpackHelperParameters2.TargetObjectType = typeof(string);
            unpackHelperParameters2.MemberName = "Name";
            unpackHelperParameters2.NilImplication = MsgPack.Serialization.NilImplication.MemberDefault;
            unpackHelperParameters2.DirectRead = this.MsgPack_Serialization_UnpackHelpers_UnpackStringValueDelegate;
            unpackHelperParameters2.Setter = this.this_SetUnpackedValueOfNameDelegate;
            MsgPack.Serialization.UnpackHelpers.UnpackReferenceTypeValue(ref unpackHelperParameters2);
        }
        
        private void SetUnpackedValueOfParameters(Metadata.HandlerInfo unpackingContext, SystemModels.PropertiesCollection unpackedValue) {
            unpackingContext.Parameters = unpackedValue;
        }
        
        private void UnpackValueOfParameters(MsgPack.Unpacker unpacker, Metadata.HandlerInfo unpackingContext, int indexOfItem, int itemsCount) {
            MsgPack.Serialization.UnpackReferenceTypeValueParameters<Metadata.HandlerInfo, SystemModels.PropertiesCollection> unpackHelperParameters3 = default(MsgPack.Serialization.UnpackReferenceTypeValueParameters<Metadata.HandlerInfo, SystemModels.PropertiesCollection>);
            unpackHelperParameters3.Unpacker = unpacker;
            unpackHelperParameters3.UnpackingContext = unpackingContext;
            unpackHelperParameters3.Serializer = this._serializer3;
            unpackHelperParameters3.ItemsCount = itemsCount;
            unpackHelperParameters3.Unpacked = indexOfItem;
            unpackHelperParameters3.TargetObjectType = typeof(SystemModels.PropertiesCollection);
            unpackHelperParameters3.MemberName = "Parameters";
            unpackHelperParameters3.NilImplication = MsgPack.Serialization.NilImplication.MemberDefault;
            unpackHelperParameters3.DirectRead = null;
            unpackHelperParameters3.Setter = this.this_SetUnpackedValueOfParametersDelegate;
            MsgPack.Serialization.UnpackHelpers.UnpackReferenceTypeValue(ref unpackHelperParameters3);
        }
        
        private void SetUnpackedValueOfWaitArray(Metadata.HandlerInfo unpackingContext, bool unpackedValue) {
            unpackingContext.WaitArray = unpackedValue;
        }
        
        private void UnpackValueOfWaitArray(MsgPack.Unpacker unpacker, Metadata.HandlerInfo unpackingContext, int indexOfItem, int itemsCount) {
            MsgPack.Serialization.UnpackValueTypeValueParameters<Metadata.HandlerInfo, bool> unpackHelperParameters4 = default(MsgPack.Serialization.UnpackValueTypeValueParameters<Metadata.HandlerInfo, bool>);
            unpackHelperParameters4.Unpacker = unpacker;
            unpackHelperParameters4.UnpackingContext = unpackingContext;
            unpackHelperParameters4.Serializer = this._serializer4;
            unpackHelperParameters4.ItemsCount = itemsCount;
            unpackHelperParameters4.Unpacked = indexOfItem;
            unpackHelperParameters4.TargetObjectType = typeof(bool);
            unpackHelperParameters4.MemberName = "WaitArray";
            unpackHelperParameters4.DirectRead = this.MsgPack_Serialization_UnpackHelpers_UnpackBooleanValueDelegate;
            unpackHelperParameters4.Setter = this.this_SetUnpackedValueOfWaitArrayDelegate;
            MsgPack.Serialization.UnpackHelpers.UnpackValueTypeValue(ref unpackHelperParameters4);
        }
        
        private void SetUnpackedValueOfWaitDataType(Metadata.HandlerInfo unpackingContext, Metadata.DataTypes unpackedValue) {
            unpackingContext.WaitDataType = unpackedValue;
        }
        
        private void UnpackValueOfWaitDataType(MsgPack.Unpacker unpacker, Metadata.HandlerInfo unpackingContext, int indexOfItem, int itemsCount) {
            MsgPack.Serialization.UnpackValueTypeValueParameters<Metadata.HandlerInfo, Metadata.DataTypes> unpackHelperParameters5 = default(MsgPack.Serialization.UnpackValueTypeValueParameters<Metadata.HandlerInfo, Metadata.DataTypes>);
            unpackHelperParameters5.Unpacker = unpacker;
            unpackHelperParameters5.UnpackingContext = unpackingContext;
            unpackHelperParameters5.Serializer = this._serializer5;
            unpackHelperParameters5.ItemsCount = itemsCount;
            unpackHelperParameters5.Unpacked = indexOfItem;
            unpackHelperParameters5.TargetObjectType = typeof(Metadata.DataTypes);
            unpackHelperParameters5.MemberName = "WaitDataType";
            unpackHelperParameters5.DirectRead = null;
            unpackHelperParameters5.Setter = this.this_SetUnpackedValueOfWaitDataTypeDelegate;
            MsgPack.Serialization.UnpackHelpers.UnpackValueTypeValue(ref unpackHelperParameters5);
        }
        
        private void SetUnpackedValueOfWaitResponse(Metadata.HandlerInfo unpackingContext, bool unpackedValue) {
            unpackingContext.WaitResponse = unpackedValue;
        }
        
        private void UnpackValueOfWaitResponse(MsgPack.Unpacker unpacker, Metadata.HandlerInfo unpackingContext, int indexOfItem, int itemsCount) {
            MsgPack.Serialization.UnpackValueTypeValueParameters<Metadata.HandlerInfo, bool> unpackHelperParameters6 = default(MsgPack.Serialization.UnpackValueTypeValueParameters<Metadata.HandlerInfo, bool>);
            unpackHelperParameters6.Unpacker = unpacker;
            unpackHelperParameters6.UnpackingContext = unpackingContext;
            unpackHelperParameters6.Serializer = this._serializer4;
            unpackHelperParameters6.ItemsCount = itemsCount;
            unpackHelperParameters6.Unpacked = indexOfItem;
            unpackHelperParameters6.TargetObjectType = typeof(bool);
            unpackHelperParameters6.MemberName = "WaitResponse";
            unpackHelperParameters6.DirectRead = this.MsgPack_Serialization_UnpackHelpers_UnpackBooleanValueDelegate;
            unpackHelperParameters6.Setter = this.this_SetUnpackedValueOfWaitResponseDelegate;
            MsgPack.Serialization.UnpackHelpers.UnpackValueTypeValue(ref unpackHelperParameters6);
        }
        
        private void SetUnpackedValueOfWaitSystemDataType(Metadata.HandlerInfo unpackingContext, Metadata.SM unpackedValue) {
            unpackingContext.WaitSystemDataType = unpackedValue;
        }
        
        private void UnpackValueOfWaitSystemDataType(MsgPack.Unpacker unpacker, Metadata.HandlerInfo unpackingContext, int indexOfItem, int itemsCount) {
            MsgPack.Serialization.UnpackValueTypeValueParameters<Metadata.HandlerInfo, Metadata.SM> unpackHelperParameters7 = default(MsgPack.Serialization.UnpackValueTypeValueParameters<Metadata.HandlerInfo, Metadata.SM>);
            unpackHelperParameters7.Unpacker = unpacker;
            unpackHelperParameters7.UnpackingContext = unpackingContext;
            unpackHelperParameters7.Serializer = this._serializer6;
            unpackHelperParameters7.ItemsCount = itemsCount;
            unpackHelperParameters7.Unpacked = indexOfItem;
            unpackHelperParameters7.TargetObjectType = typeof(Metadata.SM);
            unpackHelperParameters7.MemberName = "WaitSystemDataType";
            unpackHelperParameters7.DirectRead = null;
            unpackHelperParameters7.Setter = this.this_SetUnpackedValueOfWaitSystemDataTypeDelegate;
            MsgPack.Serialization.UnpackHelpers.UnpackValueTypeValue(ref unpackHelperParameters7);
        }
        
        protected override Metadata.HandlerInfo UnpackFromCore(MsgPack.Unpacker unpacker) {
            Metadata.HandlerInfo result = default(Metadata.HandlerInfo);
            result = new Metadata.HandlerInfo();
            if (unpacker.IsArrayHeader) {
                return MsgPack.Serialization.UnpackHelpers.UnpackFromArray(unpacker, result, MsgPack.Serialization.UnpackHelpers.GetIdentity<Metadata.HandlerInfo>(), this._memberNames, this._unpackOperationList);
            }
            else {
                return MsgPack.Serialization.UnpackHelpers.UnpackFromMap(unpacker, result, MsgPack.Serialization.UnpackHelpers.GetIdentity<Metadata.HandlerInfo>(), this._unpackOperationTable);
            }
        }
    }
}

